import { InputError } from '@backstage/errors';

/**
 * Storage keys are generated by the backend, never supplied by a client. They are still
 * validated here, because they end up in file paths and object names.
 */
const STORAGE_KEY_PATTERN = /^[0-9a-zA-Z_-]{1,64}$/;

/** @public */
export function assertValidStorageKey(storageKey: string): void {
  if (!STORAGE_KEY_PATTERN.test(storageKey)) {
    throw new InputError(`Invalid storage key '${storageKey}'`);
  }
}

/** @public */
export function assertValidChunkIndex(index: number): void {
  if (!Number.isInteger(index) || index < 0) {
    throw new InputError(`Invalid chunk index '${index}'`);
  }
}

/** @public */
export function chunkFileName(index: number): string {
  assertValidChunkIndex(index);
  return `${index}.bin`;
}
